all:
	gcc -oFileSystemNotify.exe FileSystemNotify.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oVars.exe Vars.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oParseRSS.exe ParseRSS.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oFileCopy.exe FileCopy.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oTokenize.exe Tokenize.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oSpawnContainer.exe SpawnContainer.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oMaps.exe Maps.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oTTYTest.exe TTYTest.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oSSLClient.exe SSLClient.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oErrors.exe Errors.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oPocketOAuth.exe PocketOAuth.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oMastodonOAuth.exe MastodonOAuth.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oDeviantArtOAuth.exe DeviantArtOAuth.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oGoogleOAuthImplicit.exe GoogleOAuthImplicit.c ../libUseful-2.8.a -lssl -lcrypto -lz
	gcc -oGoogleOAuthFull.exe GoogleOAuthFull.c ../libUseful-2.8.a -lssl -lcrypto -lz


#	gcc -oMSOAuth.exe MSOAuth.c ../libUseful-2.8.a -lssl -lcrypto -lz
